# Generated by Django 4.1.3 on 2022-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
